// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJBjblahfXi50CH44tCWEetqlU9hNLfY',
    appId: '1:557812236532:web:ef489dda11c51b381a5ea1',
    messagingSenderId: '557812236532',
    projectId: 'sanad-48025',
    authDomain: 'sanad-48025.firebaseapp.com',
    storageBucket: 'sanad-48025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAogvOl1DMU1VWSRU4qq8T6ALgzFQz47I4',
    appId: '1:557812236532:android:5bba1aa9944eb9c01a5ea1',
    messagingSenderId: '557812236532',
    projectId: 'sanad-48025',
    storageBucket: 'sanad-48025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMq7ZjKoXn6zVZfpqpgee8Q6GivlFJLXQ',
    appId: '1:557812236532:ios:e040e2393d0a98511a5ea1',
    messagingSenderId: '557812236532',
    projectId: 'sanad-48025',
    storageBucket: 'sanad-48025.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMq7ZjKoXn6zVZfpqpgee8Q6GivlFJLXQ',
    appId: '1:557812236532:ios:e040e2393d0a98511a5ea1',
    messagingSenderId: '557812236532',
    projectId: 'sanad-48025',
    storageBucket: 'sanad-48025.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJBjblahfXi50CH44tCWEetqlU9hNLfY',
    appId: '1:557812236532:web:44ef184b30b1d4f51a5ea1',
    messagingSenderId: '557812236532',
    projectId: 'sanad-48025',
    authDomain: 'sanad-48025.firebaseapp.com',
    storageBucket: 'sanad-48025.firebasestorage.app',
  );
}
